server {
    listen 80 default_server;
    server_name _;
    root /var/www/smbcontrol/public;
    index index.php;

    location / {
        # Esta linha faz o roteamento MVC funcionar
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock; # Ajuste para a versão do seu PHP-FPM
    }
}
